'use strict';

module.exports = [
  {
    type: 'input',
    name: 'mode',
    message: 'Mode define how you want to get or report erros',
    default: 'debounce',
  },
  {
    type: 'input',
    name: 'channels',
    message: 'list of available channels',
    default: null,
  },
  {
    type: 'list',
    name: 'agent',
    message:
      'Define the agent who report errors/hazardous behavior in your app',
    default: 'ana',
    choices: [
      'ana',
      'ange',
      'ashe',
      'baptiste',
      'bastion',
      'bouldozer',
      'brigitte',
      'chacal',
      'doomfist',
      'dva',
      'echo',
      'fatale',
      'genji',
      'hanzo',
      'lucio',
      'mccree',
      'mei',
      'moira',
      'orisa',
      'pharah',
      'faucheur',
      'reinhardt',
      'roadhog',
      'sigma',
      'soldat-76',
      'sombra',
      'symmetra',
      'torbjorn',
      'tracer',
      'winston',
      'zarya',
      'zenyatta',
    ],
  },
];
